var operations={GET_ALL:1,GET_SINGLE:2,POST_STORY:3,POST_COMMENT:4,EDIT_STORY:5,GET_SESSION:6,LOGIN_USER:7,KILL_SESSION:8,DELETE_STORY:9,ABOUT_PAGE_GET:10,ABOUT_PAGE_POST:11,GET_ALL_OFFSET:12,OLDER_EXISTS:13,SESS_COLOR:14},ANIMATION_LENGTH_DESTROYING=250,ANIMATION_LENGTH_LOADING=250,ANIMATION_LENGTH_STORIES=750,WAIT_TIME_LOADING_FROM_DB=2E3,session,sessionInfo,instances=0,offset=0;function facebookdelayedstart(){setTimeout("fbstart()",500)}function fbstart(){FB.XFBML.parse()}
function fakerandom(){var a=(new Date).getTime();return Math.floor(Math.random()*a/1E3)}function fetch(a){var b;$.ajax({dataType:"json",url:"worker.php",async:!1,type:"POST",data:a,success:function(a){b=a}}).fail(function(){console.log("failed")});return b}function animateDown(a){$(a).slideDown({queue:!1,duration:ANIMATION_LENGTH_STORIES})}function waitdestroy(a){destroy();setTimeout(a,500)}
function commentapi(a){var b=0;$.ajax({url:"https://graph.facebook.com/comments/?ids=http://beta.budzique.com/?s="+a,dataType:"json",success:function(a){var d=[];$.each(a,function(a,b){d.push(b)});b=d[0].comments;console.log(d)}}).fail(function(){console.log("failed")});return b}function getUrlVars(){var a={};window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(b,c,d){a[c]=d});return a}
function getCookie(a){var b=document.cookie,c=b.indexOf(" "+a+"=");-1==c&&(c=b.indexOf(a+"="));-1==c?b=null:(c=b.indexOf("=",c)+1,a=b.indexOf(";",c),-1==a&&(a=b.length),b=unescape(b.substring(c,a)));return b}function resetbox(a,b){a.value==b&&(a.value="")}function htmlDecode(a){var b=document.createElement("div");b.innerHTML=a;return 0===b.childNodes.length?"":b.childNodes[0].nodeValue}
function formatDate(a,b){function c(a){return 2>a.toString().length?"0"+a:a}return b.replace(/%([a-zA-Z])/g,function(b,e){switch(e){case "Y":return a.getUTCFullYear();case "M":return c(a.getUTCMonth()+1);case "d":return c(a.getUTCDate());case "H":return c(a.getUTCHours());case "m":return c(a.getUTCMinutes());case "s":return c(a.getUTCSeconds());default:throw Error("Unsupported format code: "+e);}})}
function destroy(){for(name in CKEDITOR.instances)CKEDITOR.instances[name].destroy();$(".destroyable").each(function(a){$(this).animate({height:"0px","min-height":"0px",opacity:0},ANIMATION_LENGTH_DESTROYING,function(){console.log($(this).attr("id"));$(this).remove()})})}function decimalToHex(a){if(0==a)return"00";a=Number(a).toString(16);return a="".substr(0,6-a.length)+a}
function color(){var a=$("#colorR").val(),b=$("#colorG").val(),c=$("#colorB").val();$("#r").html(decimalToHex(a));$("#g").html(decimalToHex(b));$("#b").html(decimalToHex(c));$(".content").css("background-color","rgba("+a+","+b+","+c+",0.5)");$(".sidebar1").css("background-color","rgba("+a+","+b+","+c+",0.5)");$(".sidebar2").css("background-color","rgba("+a+","+b+","+c+",0.5)")}
function saveColor(){var a=$("#colorR").val(),b=$("#colorG").val(),c=$("#colorB").val();fetch({op:operations.SESS_COLOR,r:a,g:b,b:c})}function cmize(){"none"==$("#Customize").css("display")?($("#Customize").css("height","").css("opacity",""),animateDown("#Customize")):$("#Customize").animate({height:"0px",opacity:0},ANIMATION_LENGTH_DESTROYING,function(){$("#Customize").hide()})}
function checkSession(){var a;$(".killable").animate({height:"0px","min-height":"0px",opacity:0},ANIMATION_LENGTH_DESTROYING,function(){$(this).remove()});var b=fetch({op:operations.GET_SESSION});!1==b.success?alert("Failed to load data from server! Error Message:"+b.data):a=b.data;session=a.loggedin;sessionInfo=a;if(session){var b=sessionInfo.user.username,c=sessionInfo.user.flags,d="";a=fakerandom();2<=c&&(d='<a href="#" onclick="storypostmode()">Post</a>');var e=c=255,f=255,g=getCookie("portal2SessionClr");
!1!=g&&null!=g&&(console.log(g),f=JSON.parse(g),c=f.r,e=f.g,f=f.b);$("#userPanel").append('<div id="InnerPanelSess_'+a+'" class="killable" style="display:none;"><p>Logged in as '+b+"</p><p>"+d+'</p><p><a href="#" onclick="logout()">logout</a></p><div id="Customize" style="display:none"><input type="range" id="colorR" name="colorR" min="0" max="255" value="'+c+'" onchange="color()"><span id="r">ff</span><input type="range" id="colorG" name="colorG" min="0" max="255" value="'+e+'" onchange="color()"><span id="g">ff</span><input type="range" id="colorB" name="colorB" min="0" max="255" value="'+
f+'" onchange="color()"><span id="b">ff</span><button onclick="saveColor();">Save Color</button><span id="colr">For this Session.</span></div><button onclick="cmize()">Customize</button></div>');animateDown("#InnerPanelSess_"+a+"");color()}else a=fakerandom(),$("#userPanel").append('<div id="InnerPanelDef_'+a+'" class="killable" style="display:none;"><p><a href="#" onclick="login()">Login</a></p><p><a href="#" onclick="alert(\'Registration Not available...\')">Register</a></p></div>'),animateDown("#InnerPanelDef_"+
a+"");$("#usrLoad").hide(ANIMATION_LENGTH_LOADING)}function logout(){fetch({op:operations.KILL_SESSION});init()}
function login(){$(".killable").animate({height:"0px","min-height":"0px",opacity:0},ANIMATION_LENGTH_DESTROYING,function(){$(this).remove()});var a=fakerandom();$("#userPanel").append('<div id="InnerPanelLogin_'+a+'" class="killable" style="display:none;"><p><input form="worker" type="text" name="username" id="username" value="username" onclick=\'resetbox(this, "username")\'/></p><p><input form="worker" type="password" name="password" id="password" value="password" onclick=\'resetbox(this, "password")\'/></p><p>Keep me logged in: <input form="worker" type="checkbox" name="long" id="long"/><button onclick="login1()">Log In</button></p></div>');animateDown("#InnerPanelLogin_"+
a+"")}function login1(){var a=$("[name=username]").val(),b=$("[name=password]").val(),c=$("[name=long]").val();!1==fetch({op:operations.LOGIN_USER,username:a,password:b,"long":c}).success&&alert("Invalid username or password, please try again.");checkSession()}
function storypostmode(){newsOn=!1;destroy();var a=fakerandom();$("#article1").append('<section id="section_edit_'+a+"\" class=\"destroyable\" style=\"display:none;\"><h2>Add new post</h2><input type='text' form='worker' id='title' name='title' value='title' onclick='resetbox(this, \"title\")'/><textarea rows='6' cols='50' id='editor"+instances+"' name='story' class='ckeditor' form='worker'></textarea><button onclick='poststory()'>Submit</button></section>");animateDown("#section_edit_"+a+"");$("#section_edit_"+
a+"").animate({"min-height":"200px"},{duration:ANIMATION_LENGTH_STORIES});CKEDITOR.replaceAll("ckeditor");instances+=1}
function storyeditmode(a){var b=fetch({op:operations.GET_SINGLE,story_id:a});newsOn=!1;destroy();if(!1==b.success)alert("Failed to load data from server! Error Message:"+JSON.stringify(b.data));else var c=b.data;b=fakerandom();$("#article1").append('<section id="section_edit_'+b+"\" class=\"destroyable\" style=\"display:none;\"><h2>Edit Post</h2><input type='text' form='worker' name='title' value='"+c.title+"' onclick='resetbox(this, \""+c.title+"\")'/><textarea rows='6' cols='50' id='editor"+instances+
"' name='story' class='ckeditor' form='worker'>"+c.story+"</textarea><button onclick='editstory("+a+")'>Submit</button></section>");animateDown("#section_edit_"+b+"");$("#section_edit_"+b+"").animate({"min-height":"200px"},{duration:ANIMATION_LENGTH_STORIES});CKEDITOR.replaceAll("ckeditor");instances+=1}function editstory(a){var b=getEditorContent();fetch({op:operations.EDIT_STORY,estory_id:a,story:b});destroy();init()}
function poststory(){var a=$("#title").val(),b=getEditorContent();console.log(b);fetch({op:operations.POST_STORY,author:sessionInfo.user.username,title:a,story:b});destroy();init()}function deletestory(a){confirm("Are you sure you want to delete this story?")?(fetch({op:operations.DELETE_STORY,dstory_id:a}),init()):getstory(a)}function getObjectLength(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}
function validemail(a){return RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i).test(a)}
function getEditorContent(){var a;if(1==getObjectLength(CKEDITOR.instances))for(name in CKEDITOR.instances)a=CKEDITOR.instances[name].getData();return a}
function abouteditmode(){var a=fetch({op:operations.ABOUT_PAGE_GET});newsOn=!1;destroy();if(!1==a.success)alert("Failed to load data from server! Error Message:"+JSON.stringify(a.data));else var b=a.data;a=fakerandom();$("#article1").append('<section id="section_edit_'+a+"\" class=\"destroyable\" style=\"display:none;\"><h2>Edit About Page</h2><textarea rows='6' cols='50' id='editor"+instances+"' name='about' class='ckeditor' form='worker'>"+b.about+"</textarea><button onclick='editabout()'>Submit</button></section>");
animateDown("#section_edit_"+a+"");$("#section_edit_"+a+"").animate({"min-height":"200px"},{duration:ANIMATION_LENGTH_STORIES});CKEDITOR.replaceAll("ckeditor");instances+=1}function editabout(){var a=getEditorContent();fetch({op:operations.ABOUT_PAGE_POST,about:a});about()}function titlechange(a){if($("#function").html()==a)return 0;$("#function").hide(250,function(){$(this).html(a,function(){})});$("#function").show(250)}
function contactus(){titlechange("Contact Us");newsOn=!1;destroy();var a=fakerandom();$("#article1").append('<section id="section_edit_'+a+'" class="destroyable" style="display:none;"><h2>Contact Us</h2><input type="text" name="fullname" id="fullname" /><input type="email" name="email" id="email" /><textarea rows=\'6\' cols=\'50\' id=\'editor'+instances+"' name='mail' class='ckeditor' form='worker'></textarea><button onclick='contactus1()'>Submit</button></section>");animateDown("#section_edit_"+
a+"");$("#section_edit_"+a+"").animate({"min-height":"200px"},{duration:ANIMATION_LENGTH_STORIES});CKEDITOR.replaceAll("ckeditor");instances+=1}function contactus1(){var a=$("#email").val(),b=$("#fullname").val();getEditorContent();validemail(a)?""==b&&alert("Please input your name..."):alert("Please input a valid email address...")}
function about(){titlechange("About");newsOn=!1;destroy();var a=fetch({op:operations.ABOUT_PAGE_GET});if(!1==a.success)alert("Failed to load data from server! Error Message:"+JSON.stringify(a.data));else var b=a.data;var a=fakerandom(),b=b.about,c="&nbsp;";session&&2<sessionInfo.user.flags&&(c='<a href="#" onclick="abouteditmode()">edit</a>');$("#article1").append('<section id="section_'+a+'" class="destroyable" style="display:none;">'+htmlDecode(b)+'<div class="fb-comments" data-href="http://beta.budzique.com/?s=about" data-colorscheme="light" data-numposts="5" data-width="600px"></div><p><span class="smallinfo2" >'+
c+"</span></p></section>");animateDown("#section_"+a);$("#section_"+a).animate({"min-height":"200px"},{queue:!1,duration:ANIMATION_LENGTH_STORIES});facebookdelayedstart()}
function getstory(a){destroy();newsOn=!1;a=fetch({op:operations.GET_SINGLE,story_id:a});if(!1==a.success)alert("Failed to load data from server! Error Message:"+a.data);else var b=a.data;a=fakerandom();var c=formatDate(new Date(1E3*b.date),"%M-%d %H:%m:%s"),d="&nbsp;";session&&1<sessionInfo.user.flags&&(d='<a href="#" onclick="storyeditmode('+b.id+')">edit</a>&nbsp;|&nbsp;<a href="#" onclick="deletestory('+b.id+')">delete</a>');$("#article1").append('<section id="section_'+a+'" class="destroyable" style="display:none;"><h2><a title=\'permalink\' href="http://beta.budzique.com/?s='+
b.id+'" class="storyTitle"><span class="title">'+b.title+'</span></a><span class="smallinfo">By '+b.author+" - "+c+"</span></h2><hr/><p>"+htmlDecode(b.story)+'</p><div class="fb-comments" data-href="http://beta.budzique.com/?s='+b.id+'" data-colorscheme="light" data-numposts="5" data-width="600px"></div><p><span class="smallinfo2" >'+d+"</span></p></section>");animateDown("#section_"+a);$("#section_"+a).animate({"min-height":"200px"},{queue:!1,duration:ANIMATION_LENGTH_STORIES});history.pushState("",
"Portal 2 - News","?s="+b.id);facebookdelayedstart()}function boolOldExist(){var a=fetch({op:operations.OLDER_EXISTS,curr_offset:offset});return!1==a.success?(alert("Failed to load data from server! Error Message:"+JSON.stringify(a.data)),-1):!0==a.data?!0:!1}
function oldexist(){var a=fetch({op:operations.OLDER_EXISTS,curr_offset:offset});if(!1==a.success)alert("Failed to load data from server! Error Message:"+JSON.stringify(a.data));else var b=a.data;a="";!0==b&&(b=offset+3,a+='<a href="#" onclick="initOffset('+b+')">Older Stories</a>');0<offset&&(""!=a&&(a+="&nbsp;|&nbsp;"),b=offset-3,a=a+'<a href="#" onclick="initOffset('+b+')">Newer Stories</a>');b=fakerandom();app='<section id="oldnew_'+b+'" class="destroyable" style="display:none;">'+a+"</section>";
$("#article1").append(app);$("#oldnew_"+b+"").slideDown()}var newsOn;function init(a){a="undefined"!==typeof a?a:!1;newsOn=!0;checkSession();!1!=a?getstory(a):(destroy(),a=fetch({op:operations.GET_ALL}),init1("",a));offset=0}function initOffset(a){destroy();a=fetch({op:operations.GET_ALL_OFFSET,offset:a});init1("",a)}
function getScrollBot(){o=offset+3;var a=fetch({op:operations.GET_ALL_OFFSET,offset:o});if(!1==a.success)alert("Failed to load data from server! Error Message:"+JSON.stringify(a.data));else var b=a.data;var a=fakerandom(),c;for(x in b){c=b[x];var d=formatDate(new Date(1E3*c.date),"%M-%d %H:%m:%s");c='<section id="section_'+a+'" class="destroyable" style="display:none;"><h2><a href="#" onclick="getstory('+c.id+')" class="storyTitle"><span class="title">'+c.title+'</span></a><span class="smallinfo">By '+
c.author+" - "+d+"</span></h2><hr/><p>"+htmlDecode(c.summary)+'</p><p><span class="smallinfo2" ><fb:comments-count href="http://beta.budzique.com/?s='+c.id+'"></fb:comments-count> comment(s)</span></p></section>';$("#article1").append(c);animateDown("#section_"+a);$("#section_"+a).animate({"min-height":"200px"},{queue:!1,duration:ANIMATION_LENGTH_STORIES});a++}offset=o;facebookdelayedstart()}
function init1(a,b){if(!1==b.success)alert("Failed to load data from server! Error Message:"+JSON.stringify(b.data));else var c=b.data;var d=fakerandom(),e;titlechange("News");for(x in c){e=c[x];var f=formatDate(new Date(1E3*e.date),"%M-%d %H:%m:%s");e='<section id="section_'+d+'" class="destroyable" style="display:none;"><h2><a href="#" onclick="getstory('+e.id+')" class="storyTitle"><span class="title">'+e.title+'</span></a><span class="smallinfo">By '+e.author+" - "+f+"</span></h2><hr/><p>"+htmlDecode(e.summary)+
'</p><p><span class="smallinfo2" ><fb:comments-count href="http://beta.budzique.com/?s='+e.id+'"></fb:comments-count> comment(s)</span></p></section>';$("#article1").append(e);animateDown("#section_"+d);$("#section_"+d).animate({"min-height":"200px"},{queue:!1,duration:ANIMATION_LENGTH_STORIES});d++}history.pushState("","Portal 2 - News","/");facebookdelayedstart()}function botInit(){ScrollBot=!0}function ToTop(){$("html, body").animate({scrollTop:0},1500)}
function destroyLoad(){$("#LoadOld").animate({height:"0px","min-height":"0px",opacity:0},ANIMATION_LENGTH_DESTROYING,function(){console.log($(this).attr("id"));$(this).remove()})}var ScrollBot=!0;
$(document).ready(function(){var a="",a=getUrlVars().s;""!=a?setTimeout("init("+a+");",1500):setTimeout("init();",1500);$(window).scroll(function(){$(window).scrollTop()+$(window).height()==$(document).height()&&boolOldExist()&&newsOn&&(ScrollBot&&(app='<section id="LoadOld" class="destroyable" style="display:none;">Loading Older Posts...</section>',$("#article1").append(app),$("#LoadOld").slideDown(),setTimeout("destroyLoad()",1E3),setTimeout("getScrollBot();",500+ANIMATION_LENGTH_DESTROYING)),ScrollBot=
!1,setTimeout("botInit();",1E3))})});